--!jinja
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE SCHEMA CORTEX_AGENTS_DEMO.MAIN;

CREATE OR REPLACE STAGE DOCUMENTS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );
  
CREATE OR REPLACE STAGE SEMANTIC_MODELS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

COPY FILES
  INTO @DOCUMENTS
  FROM @CORTEX_AGENTS_DEMO.PUBLIC.GITHUB_REPO_CORTEX_AGENTS_DEMO/branches/{{BRANCH}}/use_cases/main/documents/
  PATTERN='.*[.]pdf';
ALTER STAGE DOCUMENTS REFRESH;

COPY FILES
  INTO @SEMANTIC_MODELS
  FROM @CORTEX_AGENTS_DEMO.PUBLIC.GITHUB_REPO_CORTEX_AGENTS_DEMO/branches/{{BRANCH}}/use_cases/main/semantic_models/
  PATTERN='.*[.]yaml';
ALTER STAGE SEMANTIC_MODELS REFRESH;

CREATE OR REPLACE NOTEBOOK SETUP_AGENT_MAIN
    FROM '@CORTEX_AGENTS_DEMO.PUBLIC.GITHUB_REPO_CORTEX_AGENTS_DEMO/branches/{{BRANCH}}/use_cases/main' 
        MAIN_FILE = 'SETUP_AGENT_MAIN.ipynb' 
        QUERY_WAREHOUSE = COMPUTE_WH;
ALTER NOTEBOOK SETUP_AGENT_MAIN ADD LIVE VERSION FROM LAST;

-- Whether to execute the notebook or not during initial demo setup
{% if EXECUTE_NOTEBOOKS %}
    EXECUTE NOTEBOOK SETUP_AGENT_MAIN();
{%- endif -%}