name: app_environment
channels:
  - snowflake
dependencies:
  - matplotlib=3.9.2
  - networkx=*
  - plotly=5.24.1
  - seaborn=0.13.2
  - shap=0.46.0
  - snowflake-ml-python=1.7.4
  - snowflake.core=1.0.5
  - statsmodels=0.14.4
  - tabulate=*